#!/bin/sh

DIST_DIR=dist
MODULE_NAME=number_converter
DEST_PATH=$DIST_DIR/$MODULE_NAME.js

mkdir -p "$DIST_DIR"

node_modules/.bin/browserify -s $MODULE_NAME lib | node_modules/.bin/uglifyjs -c warnings=false -o "$DEST_PATH"
echo $DEST_PATH
